"""Constants for the Leopard EM package."""

CCG_NOISE_STDEV = 1.0
HISTOGRAM_NUM_POINTS = 512
HISTOGRAM_MIN = -12.5
HISTOGRAM_MAX = 22.5
HISTOGRAM_STEP = (HISTOGRAM_MAX - HISTOGRAM_MIN) / HISTOGRAM_NUM_POINTS
